// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, credit)
VALUES ($1, $2)
RETURNING id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
`

type CreateUserParams struct {
	ID     int64 `json:"id"`
	Credit int32 `json:"credit"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Credit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalLinks,
		&i.Credit,
		&i.LastCreditUpdate,
		&i.IsBanned,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsPremium,
	)
	return &i, err
}

const decrementCredit = `-- name: DecrementCredit :one
UPDATE users
SET credit = credit - $2
WHERE id = $1
RETURNING id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
`

type DecrementCreditParams struct {
	ID     int64 `json:"id"`
	Credit int32 `json:"credit"`
}

func (q *Queries) DecrementCredit(ctx context.Context, arg DecrementCreditParams) (*User, error) {
	row := q.db.QueryRow(ctx, decrementCredit, arg.ID, arg.Credit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalLinks,
		&i.Credit,
		&i.LastCreditUpdate,
		&i.IsBanned,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsPremium,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalLinks,
			&i.Credit,
			&i.LastCreditUpdate,
			&i.IsBanned,
			&i.IsDeleted,
			&i.IsVerified,
			&i.IsPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalActiveUsersCount = `-- name: GetTotalActiveUsersCount :one
SELECT COUNT(*)
FROM users
WHERE is_deleted = false
`

func (q *Queries) GetTotalActiveUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalActiveUsersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
FROM users
WHERE id = $1 AND is_deleted = false
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalLinks,
		&i.Credit,
		&i.LastCreditUpdate,
		&i.IsBanned,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsPremium,
	)
	return &i, err
}

const incrementCredit = `-- name: IncrementCredit :one
UPDATE users
SET credit = credit + $2
WHERE id = $1
RETURNING id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
`

type IncrementCreditParams struct {
	ID     int64 `json:"id"`
	Credit int32 `json:"credit"`
}

func (q *Queries) IncrementCredit(ctx context.Context, arg IncrementCreditParams) (*User, error) {
	row := q.db.QueryRow(ctx, incrementCredit, arg.ID, arg.Credit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalLinks,
		&i.Credit,
		&i.LastCreditUpdate,
		&i.IsBanned,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsPremium,
	)
	return &i, err
}

const incrementCreditWithDate = `-- name: IncrementCreditWithDate :one
UPDATE users
SET credit = credit + $2,
    last_credit_update = now()
WHERE id = $1
RETURNING id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
`

type IncrementCreditWithDateParams struct {
	ID     int64 `json:"id"`
	Credit int32 `json:"credit"`
}

func (q *Queries) IncrementCreditWithDate(ctx context.Context, arg IncrementCreditWithDateParams) (*User, error) {
	row := q.db.QueryRow(ctx, incrementCreditWithDate, arg.ID, arg.Credit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalLinks,
		&i.Credit,
		&i.LastCreditUpdate,
		&i.IsBanned,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsPremium,
	)
	return &i, err
}

const incrementTotalLinks = `-- name: IncrementTotalLinks :one
UPDATE users SET total_links = total_links + 1 WHERE id = $1 RETURNING id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
`

func (q *Queries) IncrementTotalLinks(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, incrementTotalLinks, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalLinks,
		&i.Credit,
		&i.LastCreditUpdate,
		&i.IsBanned,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsPremium,
	)
	return &i, err
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
SET
    is_banned   = $1,
    is_premium  = $2,
    is_verified = $3,
    total_links = $4
WHERE id = $5
RETURNING id, created_at, updated_at, total_links, credit, last_credit_update, is_banned, is_deleted, is_verified, is_premium
`

type UpdateUserByIDParams struct {
	IsBanned   bool  `json:"is_banned"`
	IsPremium  bool  `json:"is_premium"`
	IsVerified bool  `json:"is_verified"`
	TotalLinks int32 `json:"total_links"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserByID,
		arg.IsBanned,
		arg.IsPremium,
		arg.IsVerified,
		arg.TotalLinks,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalLinks,
		&i.Credit,
		&i.LastCreditUpdate,
		&i.IsBanned,
		&i.IsDeleted,
		&i.IsVerified,
		&i.IsPremium,
	)
	return &i, err
}
