// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DecrementCredit(ctx context.Context, arg DecrementCreditParams) (*User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetAllUsers(ctx context.Context) ([]*User, error)
	GetTotalActiveUsersCount(ctx context.Context) (int64, error)
	GetUserByID(ctx context.Context, id int64) (*User, error)
	IncrementCredit(ctx context.Context, arg IncrementCreditParams) (*User, error)
	IncrementCreditWithDate(ctx context.Context, arg IncrementCreditWithDateParams) (*User, error)
	IncrementTotalLinks(ctx context.Context, id int64) (*User, error)
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
